Repository The-unsaved/HeadingCoding, pull requests merged in 2021-09, with the labels that each got.

#2 가운데 글자 가져오기 (JS/Chaewoon)
  img/Chaewoon/가운데-글자-가져오기.png
  img/Chaewoon/두-정수-사이의-합.png
  가운데 글자 가져오기/JS/Chaewoon/README.md
  가운데 글자 가져오기/JS/Chaewoon/가운데-글자-가져오기.js
Labels: Solved

#1 직사각형 별찍기 java/kyungjun
  .gitignore
  img/kyungjun/직사각형-별찍기.png
  직사각형 별찍기/java/kyungjun/README.md
  직사각형 별찍기/java/kyungjun/kyungjun.java
Labels: Solved

#6 10부제
  10부제/js/taehwan/introduce.md
  10부제/js/taehwan/tenpart.js
Labels: Solved

#7 [ADD] 최솟값 구하기
  최솟값 구하기/js/taehwan/arrmin.js
  최솟값 구하기/js/taehwan/introduce.md
Labels: Solved

#8 [ADD] 최솟값 구하기
  10부제/js/Chaewoon/README.md
  10부제/js/Chaewoon/최솟값-구하기.js
Labels: Solved

#10 파일 이동 10부제 -> 최솟값 구하기
  최솟값 구하기/js/Chaewoon/README.md
  최솟값 구하기/js/Chaewoon/최솟값-구하기.js
Labels: question

#11 x만큼 간격이 있는 n개의 숫자
  img/kyungjun/x만큼-간격이-있는-n개의-숫자.png
  x만큼 간격이 있는 n개의 숫자/java/kyungjun/README.md
  x만큼 간격이 있는 n개의 숫자/java/kyungjun/kyungjun.java
Labels: Solved

#9 서울에서 김서방 찾기
  img/youhyun/서울에서_김서방_찾기.png
  img/youhyun/수박수박수박수박수박수?.png
  서울에서 김서방 찾기/js/youhyun/README.md
  서울에서 김서방 찾기/js/youhyun/youhyun.js
  수박수박수박수박수박수?/js/youhyun/README.md
  수박수박수박수박수박수?/js/youhyun/youhyun.js
Labels: Solved

#12 [ADD] 수박수박수박수박수? (추가 내용)
  수박수박수박수박수박수?/js/youhyun/README.md
Labels: documentation

#13 [ADD] 삼각형 판별하기
  .DS_Store
  삼각형 판별하기/js/taehwan/introduce.md
  삼각형 판별하기/js/taehwan/samgak.js
Labels: Solved

#14 행렬의 덧셈
  img/kyungjun/행렬의-덧셈.png
  행렬의 덧셈/java/kyungjun/README.md
  행렬의 덧셈/java/kyungjun/kyungjun.java
Labels: Solved

#16 [ADD] 일곱난쟁이 문제 추가
  일곱난쟁이/js/taehwan/introduce.md
  일곱난쟁이/js/taehwan/nanjang2.js
Labels: Solved

#17 [수박수박수박수박수?] 문제의 img 이름 변경 및 경로 수정 + [내적]문제 풀이
  img/youhyun/내적.png
  img/youhyun/수박.png
  내적/js/youhyun/README.md
  내적/js/youhyun/youhyun.js
  수박수박수박수박수박수?/js/youhyun/README.md
Labels: bug, Solved

#20 [ADD] A를 #으로
  A를#으로/js/taehwan/atoshop.js
  A를#으로/js/taehwan/introduce.md
Labels: Solved

#19 완주하지 못한 선수
  .DS_Store
  img/youhyun/완주하지_못한_선수.png
  완주하지 못한 선수/js/youhyun/README.md
  완주하지 못한 선수/js/youhyun/youhyun.js
Labels: Solved

#18 Kyungjun
  img/kyungjun/평균-구하기.png
  평균 구하기/java/kyungjun/README.md
  평균 구하기/java/kyungjun/kyungjun.java
Labels: Solved

#21 하샤드 수
  img/kyungjun/하샤드-수.png
  하샤드 수/java/kyungjun/README.md
  하샤드 수/java/kyungjun/kyungjun.java
Labels: Solved

#25 [ADD] 행렬의-덧셈
  img/hyunin/행렬의-덧셈.png
  행렬의 덧셈/java/hyunin/README.md
  행렬의 덧셈/java/hyunin/hyunin.java
Labels: Solved
